def parks_with_locations

parks = [
"McCarren Park",
"Mckinley Park",
"Prospect Park",
"Central Park",
"Inwood Hill Park",
"John Jay Park",
"Battery Park",
"Riverside Park",
"Linden Park",
"Astoria Park",
"P.S. 143 Armstrong Playground",
"Frank O'connor Park",
"Flushing Meadows Corona Park",
"Van Cortlandt Park",
"Williamsbridge Oval Playground",
"Ferry Point Park",
"Maurice Muller Park",
"Pelham Bay Park",
"St. James Park",
"Windmuller Park",
"Bronx Park",
"Kossuth Playground",
"Inwood Hill-Isham Park",
"Russell Pederson Playground",
"Shore Road Park",
"Harlem River Park",
"Crames Square",
"Maria Hernandez Pushcart",
"Sunset Park Pushcart",
"St. Nicholas Terrace Pushcart",
"Asser Levy Recreation Center Pushcart",
"Pushcart",
"Corona Golf Playground",
"MONTALI R0050011, JOSEPH",
"Park Cafe East",
"Tweety's Mobile Food Truck",
"Rose Hill Park",
"PS 100 Playground Trucks",
"Sakura Park",
"Dyker Beach Park",
"Annunciation Park",
"East River Park",
"Bloomingdale Park",
"Hugh Grant Circle",
"Chet Henderson",
"YAKUBOV, GAVRIEL",
"Ocean Parkway Malls Cart",
"Prospect Park Parade Ground Cart",
"Sunset Park",
"Prospect Park Mount",
"Inwood Hill Park Cart",
"Riverside Park Cart",
"Williamsbridge Oval Park",
"Harris Park Cart",
"Central Pary Gourmet Cart",
"Central Park Gourmet Carts",
"ALEX LINDOWER PARK TRUCKS",
"Highbridge Park Food Truck",
"Highbridge Park Food Trucks",
"Melt Bakery",
"Seth Low Park Mobile Food Truck",
"J.J. Byrne Memorial Park Mobile Food Truck",
"Red Hook Recreation Center Mobile Food Truck",
"Colonel Markus Playground Mobile Food Truck",
"Paul W. Kolbert Park Mobile Food Truck",
"Coney Island Beach Mobile Food Truck",
"Brooklyn Queens Expressway Mobile Food Truck",
"Fox Playground Mobile Food Truck",
"William E. Kelly Park Mobile Food Truck",
"Jackie Robinson Park Mobile Food Truck",
"Anibal Aviles Playground Mobile Food Truck",
"Audubon Playground Mobile Food Truck",
"Highbridge Park Mobile Food Truck",
"Inwood Hill Park Mobile Food Truck",
"Juniper Valley Park Mobile Food Truck",
"Crocheron Park Mobile Food Truck",
"P.S. 10 Playground Mobile Food Truck",
"Cunningham Park Mobile Food Truck",
"Grover Cleveland park Mobile Food Truck",
"Linden Park Mobile Food Truck",
"Kissena Corridor Park Mobile Food Truck",
"Thomas J. Travers Playground Mobile Food Truck",
"PS 176 Playground Mobile Food Truck",
"PS 173 Playground Mobile Food Truck",
"Vleigh Place Playground Mobile Food Truck",
"Frederick Cabbell Park Mobile Food Truck",
"Colden Playground Mobile Food Truck",
"PS 127 Elmhurst Playground Mobile Food Truck",
"JHS 93/Ridgewood Playground",
"Astoria Park Mobile Food Truck",
"East Springfield Playground Mobile Food Truck",
"Lt. Corp. Noonan Park Mobile Food Truck",
"Triborough Bridge Playground Mobile Food Truck",
"Gorman Playground Mobile Food Truck",
"Edward Byrne Park Mobile Food Truck",
"Flushing Meadows Corona Park Mobile Food Truck",
"McNeil Park Mobile Food Truck",
"Bloomingdale Park Mobile Food Truck",
"Claremont Park Mobile Food Truck",
"Slattery Playground Mobile Food Truck",
"Woodlawn Memorial Park Mobile Food Truck",
"Sound View Park Mobile Food Truck",
"Waterbury Playground Mobile Food Truck",
"Devoe Park Mobile Food Truck",
"Vinmont Veteran Park Mobile Food Truck",
"Bronx River Houses Playground Mobile Food Truck",
"P.S. 106 Playground Mobile Food Truck",
"Alfred Loreto Park Mobile Food Truck",
"Matthew & Muliner Playground Mobile Food Truck",
"Haffen Park Mobile Food Truck",
"Bronx Park Mobile Food Truck",
"Bronx Park East Mobile Food Truck",
"Seton Park Mobile Food Truck",
"Marble Hill Playground Mobile Food Truck",
"Arcilla JHS 145 Playground Mobile Food Truck",
"Space Time Playground Mobile Food Truck",
"Mapes Avenue Ballfields Mobile Food Truck",
"Barretto Point Park Mobile Food Truck",
"Pelham Bay Park Mobile Food Truck",
"L. Zimmerman Playground Mobile Food Truck",
"Van Cortlandt Park Mobile Food Truck",
"Hickman Playground Mobile Food Truck",
"Gunn Hill Houses Playground Mobile Food Truck",
"Peace Park/Cleopatra Plgd Mobile Food Truck",
"Webster Avenue Community Plgd. Mobile Food Truck",
"Athens Square Park Mobile Food Truck",
"Castle Hill Playground Mobile Food Truck",
"Owls Head Park Mobile Food Truck",
"Kissena Park Mobile Food Truck",
"Utopia Playground Mobile Food Truck",
"Clawson Playground Mobile Food Truck",
"People's Park Mobile Food Truck",
"Kelly Playground Mobile Food Truck",
"Socrates Sculpture Park Mobile Food Truck",
"Louis C. Moser Park Mobile Food Truck",
"Joseph Austin Playground Mobile Food Truck",
"Marine Park Mobile Truck",
"Martin Luther Playground Mobile Truck",
"PAPAZIAN Q3400006, AKOP",
"MONTALI R0790004, JOSEPH",
"Slattery Playground Mobile Truck",
"Pugsley Park Mobile Food Truck",
"Woodlawn Memorial Mobile Food Truck",
"Watson Park Mobile Truck",
"Harris Park Mobile Truck",
"Rainey Park Mobile Truck",
"Leo Ehrenreich Playground Mobile Food Trucks",
"St. Michael's Plgd. Mobile Food Truck",
"Rufus King Playground Trucks",
"Mccarren Park Mobile Trucks",
"Charles Drew Memorial Park Mobile Ice Cream Truck",
"Queensbridge Park Mobile Ice Cream Truck",
"Yellowstone Municipal Playground Mobile Food Truck",
"Greenbelt Recreation Center Mobile Food Truck",
"Crotona Park Mobile Food Truck",
"Loeb Boathouse Restaurant",
"Tavern on the Green",
"New Leaf Cafe",
"West 79th Street Boat Basin Cafe",
"Clearview Cafe",
"Terrace on the Park",
"World's Fair Marina Restaurant",
"South Shore Country Club",
"The Vanderbilt at South Beach",
"The Lake Club",
"Dyckman Marina Restaurant",
"Battery Gardens Restaurant",
"Union Square Seasonal Cafe",
"Arthur Kill Road Restaurant",
"Golden Ring, Inc.",
"Conservatory Water Snack Bar",
"Mineral Springs Cafe",
"Central Park Conservancy",
"Ballfields Cafe",
"North Meadow Recreation Center Snack Bar",
"Arsenal Snack Bar",
"Dag Hammarskjold Plaza Cafe",
"Shake Shack",
"Ellington In The Park",
"Pier I Cafe",
"Rockaway Beach Snack Bars",
"Astoria Pool Snack Bar",
"Ederle Terrace Snack Bar",
"Olmsted Cafeteria",
"Rodman's Neck Snack Bar",
"Orchard Beach Snack Bar",
"Dunkin' Donuts",
"Wendy's",
"Crossroads To Go",
"Harlem Meer Snack Bar",
"First Park Outdoor Cafe",
"Peter Minuit Snack Bar",
"Battery Park Snack Bar",
"Dredsurfer LLC",
"Sigmund Pretzel Shop",
"Rouge Tomate",
"NY Dosas",
"Otto Enoteca Pizzeria Gelato Cart",
"B.W.H. Trading Cart",
"People's Choice Mobile Kitchen",
"Wafels & Dinges",
"El Olomega Red Hook Salvadoran Pupusa",
"Calexico Carne Asada",
"Je & Jo Comestible Specialty",
"Soho Square Gourmet Carts",
"Little Red Square Gourmet Carts",
"Adameric Cart",
"GROM",
"CC Moore Homestead Park Fruit and Vegetable Cart",
"Hugh Grant Circle Fruit and Vegetable Cart",
"Owen Dolen Fruit and Vegetable Cart",
"McKinley Plaza Fruit & Vegetable Cart"
]

end
